url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Portfolio
email: anoushka.shrestha111@gmail.com

# Team names, titles and social links
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty